version: '3.9'
services:
  sgu-auth-service:
    image: sgu-auth-service
    build: .
    ports:
      - "8081:8081"
    container_name: sgu-auth-service
    command: mvn spring-boot:run
    networks:
      - sgu-networks
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://backend-db:5432/sgu
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - backend-db
      - keycloak
    volumes:
      - ./storage:/app/storage

  backend-db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: sgu
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: America/Sao_Paulo
    ports:
      - "5433:5432"
    expose:
      - "5432"
    networks:
      - sgu-networks
    volumes:
      - pg-data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.0
    ports:
      - "9090:8080"
    networks:
      - sgu-networks
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: password
      KC_DB_SCHEMA: public
    command: start-dev --import-realm
    depends_on:
      - keycloak-db
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json

  keycloak-db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: America/Sao_Paulo
    ports:
      - "5434:5432"
    networks:
      - sgu-networks
    volumes:
      - keycloak-pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    driver: local
  keycloak-pg-data:
    driver: local

networks:
    sgu-networks:
        external: true