version: '3.9'
services:
  backend:
    image: sgi-backend
    build: .
    ports:
      - "8081:8081"
    command: mvn spring-boot:run
    networks:
      - sgi-networks
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://backend-db:5432/sgi
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - backend-db
      - keycloak

  backend-db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: sgi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: America/Sao_Paulo
    ports:
      - "5433:5432"
    expose:
      - "5432"
    networks:
      - sgi-networks
    volumes:
      - pg-data:/var/lib/postgresql/data
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - "8080:8080"
    networks:
        - sgi-networks
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: password
    command: start-dev
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: America/Sao_Paulo
    ports:
      - "5434:5432"
    expose:
      - "5432"
    networks:
        - sgi-networks
    volumes:
      - keycloak-pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    driver: local
  keycloak-pg-data:
    driver: local

networks:
    sgi-networks:
        driver: bridge