# src/main/resources/application.yml
server:
  port: 8081

spring:
  application:
    name: sgi-back
  web:
    locale-resolver: fixed
    locale: pt_BR
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/sgi
    username: postgres
    password: baryonmode
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/sgi
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          jwk-set-uri: ${spring.security.oauth2.client.provider.keycloak.issuer-uri}/protocol/openid-connect/certs
logging:
  level:
    org:
      springframework: DEBUG
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://backend-db:5432/sgi
    username: postgres
    password: baryonmode
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/lmts/protocol/openid-connect/certs